In [2]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("shivamb/netflix-shows")

print("Path to dataset files:", path)

Downloading to C:\Users\Yusuf Solomon\.cache\kagglehub\datasets\shivamb\netflix-shows\5.archive...

100%|██████████| 1.34M/1.34M [00:16<00:00, 83.1kB/s]

Extracting files...
Path to dataset files: C:\Users\Yusuf Solomon\.cache\kagglehub\datasets\shivamb\netflix-shows\versions\5

In [4]:
import pandas as pd
import os

# Load the dataset into a DataFrame 
df = pd.read_csv(os.path.join(path, "netflix_titles.csv"), encoding="latin-1")

# View the data
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [5]:
# Show info - investigating missing values and data types
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   str
 1   type          8807 non-null   str
 2   title         8807 non-null   str
 3   director      6173 non-null   str
 4   cast          7982 non-null   str
 5   country       7976 non-null   str
 6   date_added    8797 non-null   str
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   str
 9   duration      8804 non-null   str
 10  listed_in     8807 non-null   str
 11  description   8807 non-null   str
dtypes: int64(1), str(11)
memory usage: 825.8 KB

In [10]:
df.dropna(subset=["rating", "duration"], inplace = True)

df.info()

<class 'pandas.DataFrame'>
Index: 8800 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8800 non-null   str
 1   type          8800 non-null   str
 2   title         8800 non-null   str
 3   director      6169 non-null   str
 4   cast          7975 non-null   str
 5   country       7970 non-null   str
 6   date_added    8790 non-null   str
 7   release_year  8800 non-null   int64
 8   rating        8800 non-null   str
 9   duration      8800 non-null   str
 10  listed_in     8800 non-null   str
 11  description   8800 non-null   str
dtypes: int64(1), str(11)
memory usage: 893.8 KB

In [12]:
df.fillna({"director": "Unknown", "cast": "Unknown", "country": "Unknown"}, inplace = True)

df.info()

<class 'pandas.DataFrame'>
Index: 8800 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8800 non-null   str
 1   type          8800 non-null   str
 2   title         8800 non-null   str
 3   director      8800 non-null   str
 4   cast          8800 non-null   str
 5   country       8800 non-null   str
 6   date_added    8790 non-null   str
 7   release_year  8800 non-null   int64
 8   rating        8800 non-null   str
 9   duration      8800 non-null   str
 10  listed_in     8800 non-null   str
 11  description   8800 non-null   str
dtypes: int64(1), str(11)
memory usage: 893.8 KB

In [13]:
df.dropna(subset=["date_added"], inplace = True)

df.info()

<class 'pandas.DataFrame'>
Index: 8790 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8790 non-null   str
 1   type          8790 non-null   str
 2   title         8790 non-null   str
 3   director      8790 non-null   str
 4   cast          8790 non-null   str
 5   country       8790 non-null   str
 6   date_added    8790 non-null   str
 7   release_year  8790 non-null   int64
 8   rating        8790 non-null   str
 9   duration      8790 non-null   str
 10  listed_in     8790 non-null   str
 11  description   8790 non-null   str
dtypes: int64(1), str(11)
memory usage: 892.7 KB

In [14]:
df_no_duplicates = df[~df.duplicated(keep=False)]
df_no_duplicates.info()

<class 'pandas.DataFrame'>
Index: 8790 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8790 non-null   str
 1   type          8790 non-null   str
 2   title         8790 non-null   str
 3   director      8790 non-null   str
 4   cast          8790 non-null   str
 5   country       8790 non-null   str
 6   date_added    8790 non-null   str
 7   release_year  8790 non-null   int64
 8   rating        8790 non-null   str
 9   duration      8790 non-null   str
 10  listed_in     8790 non-null   str
 11  description   8790 non-null   str
dtypes: int64(1), str(11)
memory usage: 892.7 KB

In [19]:
## No duplicates in the dataset. we are all good

df["date_added"] = pd.to_datetime(df["date_added"].str.strip(), format='%B %d, %Y')

df.info()

<class 'pandas.DataFrame'>
Index: 8790 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8790 non-null   str
 1   type          8790 non-null   str
 2   title         8790 non-null   str
 3   director      8790 non-null   str
 4   cast          8790 non-null   str
 5   country       8790 non-null   str
 6   date_added    8790 non-null   datetime64[us]
 7   release_year  8790 non-null   int64
 8   rating        8790 non-null   str
 9   duration      8790 non-null   str
 10  listed_in     8790 non-null   str
 11  description   8790 non-null   str
dtypes: datetime64[us](1), int64(1), str(10)
memory usage: 892.7 KB

In [20]:
exempted_cols = ["description", "rating", "duration"]

for col in df.columns:
    if df[col].dtype == "object":
        if col in exempted_cols:
            continue
        df[col] = df[col].str.strip().str.lower()

df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,Unknown,United States,2021-09-25,2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,Unknown,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",Unknown,2021-09-24,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,Unknown,Unknown,Unknown,2021-09-24,2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,Unknown,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [21]:
df.to_csv("netflix_titles_cleaned.csv", index=False)

In [22]:
df["rating"].unique()

<StringArray>
[   'PG-13',    'TV-MA',       'PG',    'TV-14',    'TV-PG',     'TV-Y',
    'TV-Y7',        'R',     'TV-G',        'G',    'NC-17',       'NR',
 'TV-Y7-FV',       'UR']
Length: 14, dtype: str

In [23]:
df["type"].unique()

<StringArray>
['Movie', 'TV Show']
Length: 2, dtype: str